### ISSUE TITLE
Improve docker docs

### ISSUE THREAD

**Issue by manulera** [manulera/ShareYourCloning#15]
A bit more detailed

**Comment by JamesBagley** [comment]
I took some notes on how to deploy it on a github codespace, 

> ### Building a self-hosted ShareYourCloning demo on github codespaces
> ##### Note: Github codespaces aren't meant to be left running permanently and will shut down after a period of inactivity
> Click the menu at the top left of the github website then click codespaces
> in the "quick start templates" select the Blank option
> Under Start, select "Clone Git Repository", then "Clone from Github" and type "manulera/Shareyourcloning" into the search bar
> Click Ok, then Open
> In the terminal enter `docker-compose up`
> Once complete a popup will appear saying port 8000 is now available, click "Open in Browser" to navigate to your own version of the ShareYourCloning app
> Optional: To share with other users, navigate to the ports tab of the github codespace and right click and change port visibility to public

**Comment by manulera** [comment]
Thanks @JamesBagley I tried that and added your instructions to the readme!
