### ISSUE TITLE
Can't access examples on self-hosted builds

### ISSUE THREAD

**Issue by JamesBagley** [manulera/ShareYourCloning#20]
After deploying with docker the example json files don't seem to be included.

Selecting one of the examples e.g. Gibson assembly results in nothing happening on-screen and a `GET /examples/gibson_assembly.json HTTP/1.1" 404 Not Found` message in the terminal

Templates do seem to work fine though, and all of the functionality of the website is there

**Comment by manulera** [comment]
Hi @JamesBagley thanks for testing! I fixed this in https://github.com/manulera/ShareYourCloning_backend/pull/165/commits/d5833a6c427b0dcfa7f4988fccbc9008ba2fd7d1

I would have liked to add to dockerhub, but I want to double-check other tweaks I added as well, so I will do it early next week. We have all learnt the hard way today not to push to production on Friday ;)

**Comment by manulera** [comment]
Should be working now!

**Comment by JamesBagley** [comment]
Works like a charm! 👍
