### ISSUE TITLE
Automate docker hub update

### ISSUE THREAD

**Issue by NicolasCARPi** [manulera/ShareYourCloning#25]
Currently the Action can only be manually triggered. It would be best to automatically publish a `:latest` on all commits to `master` and tagged versions when you publish tags/releases (+ optionally a `stable` tag for the stable releases).

**Comment by manulera** [comment]
Hi @NicolasCARPi I did this today.

The way it works is:

* Whenever a push is made to master in the backend or frontend repository, there is a push to dockerhub with `latest`
  * For the frontend repository, and extra `latest-syc-base` is also published, with the `/syc/` backend settings.
* When a release is made from the backend / frontend, an image tagged with the version number is published, as well as a `prod` tagged image.
  * In the frontend the `syc-base` versions are also included
* This means that:
  * `latest`: latest master
  * `prod`: latest release

In this repository, for the image that combines both frontend and backend, it's similar but I will still trigger the releases by hand, just to make sure that both frontend and backend are in sync with each other, so you can use `latest` and `prod` as before, as well as the release tag. Also, the release contains info of the release tags of backend and frontend.

A bit confusing admittedly but I think the tags in docker-hub are self-explaining:

https://hub.docker.com/repository/docker/manulera/shareyourcloning/tags

**Comment by manulera** [comment]
You can also access the version in the app now:

https://shareyourcloning.org/ At about > App version

And in the API:

https://shareyourcloning.api.genestorian.org/version

**Comment by manulera** [comment]
Hey @NicolasCARPi how is it going? Do you think you can give me a version to start from sometime soon?

**Comment by NicolasCARPi** [comment]
I will come back to you soon, yes.
